### PR TITLE
set up with electron react and started deployments endpoints

### PR DESCRIPTION
**Pull request by bemijonathan**

### CODE REVIEW

**Review by phirmware — APPROVED** [review]

**Comment by phirmware** [comment]
@bemijonathan  Conflicts

**Comment by phirmware** [comment]
I think I'll stop working on the master branch since we both contributing now.
We could make it one commit per PR so commits could be easy to organize.
We rebase over master and amend updates to keep it at one commit
What do you think?

**Comment by bemijonathan** [comment]
> I think I'll stop working on the master branch since we both contributing now.
> We could make it one commit per PR so commits could be easy to organize.
> We rebase over master and amend updates to keep it at one commit
> What do you think?

sure

@phirmware loll gotcha I will check it out

**Comment by phirmware10** [comment]
see this night crawler!
I sent that message around 12 am, that means you were awake around 2 to 3 am

**Comment by phirmware10** [comment]
Please review that my recent push also 🙏🏽

**Comment by bemijonathan** [comment]
@phirmware  check I updated the PR I think we still need to talk about the go mod stuff i don't know if i am right or you are. also add me to the frontend repo so I can push the electron.

**Review by phirmware — APPROVED** [review]

**Pull request merged**
